services:
  web:
    build:
      context: .
    container_name: virustotal_scanner_web
    ports:
      - "5000:5000" # Optional now that Nginx will be used
    volumes:
      - uploads_data:/app/uploads
    env_file:
      - .env
    environment:
      - FLASK_CONFIG=${FLASK_CONFIG:-production}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: virustotal_scanner_nginx
    ports:
      - "80:80" # This is where Nginx will listen (you'll visit http://localhost)
    volumes:
      - ./nginx/flask_app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: unless-stopped

volumes:
  uploads_data:
